name: 'cmake'
description: 'CMake setup for Audio'
runs:
  using: composite
  steps:
    - name: Configure
      shell: bash
      run: cmake -DCMAKE_BUILD_TYPE=Release -DJUCE_COPY_PLUGIN_AFTER_BUILD=ON -B build -S .

    - name: Build
      shell: bash
      run: cmake --build build --config Release -j 4
    
    - name: Tests
      shell: bash
      run: ctest --test-dir build -C Release --output-on-failure

# Want to be able to run this in this action. Unfortunately macos does not yet seems to support running docker containers
    # - name: Generate documentation
      # shell: bash
      # run: cmake --build build --target docs --config Release -j 4



      

