name: Audio Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    name: Deploy Doxygen documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Configure Doxygen
        run: cmake --preset Docs

      - name: Generate Documentation
        run: cmake --build --preset Docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/docs/html
